# 服务器配置
server:
  port: 8086
  address: 0.0.0.0  # 监听所有网络接口，允许局域网访问
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring配置
spring:
  application:
    name: video-parsing-api
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_parsing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: your_password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: VideoParsingHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  
  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

# 日志配置
logging:
  level:
    com.video: DEBUG
    com.video.interceptor: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/video-parsing.log
    max-size: 10MB
    max-history: 30

# 微信小程序配置
wechat:
  miniapp:
    app-id: your_wechat_appid
    app-secret: your_wechat_app_secret
    # 微信API地址
    api:
      code2session: https://api.weixin.qq.com/sns/jscode2session

# 外部API配置
external:
  watermark:
    # 去水印API配置
    domain: your-api-domain.com
    app-id: your_api_app_id
    url: https://{domain}/Watermark/Index
    timeout: 30000

# 去水印API配置
watermark:
  api:
    url: https://your-api-domain.com/Watermark/Index
    appid: your_api_app_id

# 代理配置
proxy:
  domain: https://domain.com
  # 是否启用代理模式
  enabled: true

# 业务配置
business:
  # 签到配置
  sign:
    daily-points: 10
    continuous-bonus: 5
  # 解析记录保留时间（分钟）
  parsing-record-retention-minutes: 30
  # 用户配置
  user:
    default-points: 100